services:
  - docker:19.03.1-dind

image: docker:19.03.1

python-package-build:
  tags:
    - docker
    - dind
    - build
  stage: build
  image: pypy:3
  script:
    - export
    - python setup-izaber.py sdist bdist_wheel --universal
  only:
    - tags
  artifacts:
    paths:
      - dist/

docker-build-deploy:
  tags:
    - docker
    - dind
    - build
  stage: test
  dependencies:
    - python-package-build
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    RELEASE_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker run --name 'nexus' -v `pwd`/tests:/app/tests --rm $IMAGE_NAME python /app/tests/run-tests.py
    - docker push $IMAGE_NAME
    - docker build -t $RELEASE_IMAGE_NAME .
    - docker push $RELEASE_IMAGE_NAME

python-package-deploy:
  tags:
    - docker
    - dind
    - build
  stage: deploy
  image: pypy:3
  dependencies:
    - python-package-build
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*


